version: "3.3"

networks:
  kodzuverse:
    driver: bridge
    name: kodzuverse_network

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - kodzuverse

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - kodzuverse
