networks:
  kodzuverse:
    driver: bridge
    name: kodzuverse_network

services:
  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg18
    restart: always
    shm_size: 256mb
    volumes:
      - ./data/postgres:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - kodzuverse

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9
    restart: always
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - kodzuverse

